name: RRG-FrontEnd-Deploy

on:
  workflow_run:
    workflows: ["RRG-FrontEnd-Build"]
    types:
      - completed
    branches:
      - testing

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    permissions:
      actions: read
      contents: read

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: RRG-FrontEnd-Build
          path: dist
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB }}

      - name: Remove old build files
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            sudo rm -rf ${{ secrets.DEV_TARGET_PATH }}

      - name: Copy dist to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "dist/*"
          target: ${{ secrets.DEV_TARGET_PATH }}
          strip_components: 1

      - name: Deploy on Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            sudo systemctl restart nginx
