name: RRG-FrontEnd-Testing

on:
  push:
    branches:
      - testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies
        run: npm install --force

      - name: Build React App
        env:
          VITE_API_BASE_URL: ${{ secrets.TESTING_VITE_API_BASE_URL }}
          VITE_API_TIMEOUT: ${{ secrets.VITE_API_TIMEOUT }}
          VITE_APP_NAME: ${{ secrets.VITE_APP_NAME }}
          VITE_APP_VERSION: ${{ secrets.VITE_APP_VERSION }}
          VITE_ENV: ${{ secrets.VITE_ENV }}
        run: npm run build

      - name: Remove old testing build
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            sudo rm -rf ${{ secrets.TESTING_TARGET_PATH }}

      - name: Copy Build to Testing Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "dist/*"
          target: ${{ secrets.TESTING_TARGET_PATH }}
          strip_components: 1

      - name: Restart Nginx
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            sudo systemctl restart nginx
